<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0;net48</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Authors>Gabriel Mateos</Authors>
    <Description>Sha256Helper library (net9 + net48 COM legacy).</Description>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net48'">
    <ComVisible>true</ComVisible>
    <PlatformTarget>x86</PlatformTarget>
    <Prefer32Bit>true</Prefer32Bit>
  </PropertyGroup>
</Project>
